version: "3"
services: 

  scraper:
    build: ./scraper
    volumes: 
      - "./scraper/src:/usr/local/app/src:rw"
      - "./archive:/usr/local/app/archive:rw"
    entrypoint: python3 src/server.py
    ports:
      - 5005:5000

  citator:
    build: ./citator
    volumes:
      - "./citator/src:/usr/local/app/src:rw"
      - "./citator/resources:/usr/local/app/resources:rw"
      - "./citator-data:/usr/local/app/data:rw"
      - "./archive:/usr/local/app/resources/public/archive:rw"
    # entrypoint: clj -M:nREPL -m nrepl.cmdline -p 47482 -b 0.0.0.0
    entrypoint: clj -M -m server
    ports:
      - 3005:3000
      - 47482:47482

  citator-ui:
    build: ./citator-ui
    volumes:
      - "./citator-ui/src:/usr/local/app/src:rw"
    entrypoint: npx shadow-cljs watch app
    ports: 
      - 8020:8020
      - 9630:9630

  doi-registrar:
    build: ./doi-registrar
    volumes:
      - "./doi-registrar/src:/usr/local/app/src:rw"
      - "./doi-registrar/resources:/usr/local/app/resources:rw"
      - "./doi-registrar-data:/usr/local/app/data:rw"
    # entrypoint: clj -M:nREPL -m nrepl.cmdline -p 47483 -b 0.0.0.0
    entrypoint: clj -M -m server
    ports:
      - 3006:3000
      - 47483:47483

  doi-registrar-ui:
    build: ./doi-registrar-ui
    volumes:
      - "./doi-registrar-ui/src:/usr/local/app/src:rw"
    entrypoint: npx shadow-cljs watch app
    ports: 
      - 8021:8021
      - 9631:9631
